# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full


# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.abspath("../src"))


# -- Project information -----------------------------------------------------

project = "OMOTES Simulator documentation"
copyright = "2024, NieuweWarmteNu Design Toolkit"
author = "Michiel Tukker, Sam van der Zwan, Ryvo Octaviano, Mike van Meerkerk"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
]

autodoc_mock_imports = ["geopandas", "plotly", "shapely"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "venv"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


def run_apidoc(_app):
    """Generate API docs for omotes_simulator_core packages."""
    from sphinx.ext.apidoc import main as apidoc_main

    doc_dir = Path(__file__).resolve().parent
    output_dir = doc_dir / "developer" / "api"
    module_dir = doc_dir.parent / "src" / "omotes_simulator_core"

    output_dir.mkdir(parents=True, exist_ok=True)

    apidoc_main(
        [
            "--force",
            "--module-first",
            "--separate",
            "--output-dir",
            str(output_dir),
            str(module_dir),
        ]
    )

    normalize_apidoc_titles(output_dir)


def normalize_apidoc_titles(output_dir: Path) -> None:
    """Normalize autogenerated API page titles for readable developer navigation."""
    heading_re = re.compile(r"^[=\-~`^\"+#*]+$")

    for rst_file in output_dir.glob("*.rst"):
        lines = rst_file.read_text(encoding="utf-8").splitlines()
        if len(lines) < 2:
            continue

        title = lines[0].replace(r"\_", "_")

        if title.startswith("omotes_simulator_core."):
            title = title[len("omotes_simulator_core.") :]
        elif title.startswith("omotes_simulator_core"):
            title = title[len("omotes_simulator_core") :].strip()

        title = re.sub(r"\s*package$", "", title).strip()
        title = re.sub(r"\s*module$", "", title).strip()

        if not title:
            title = "API root"

        if heading_re.match(lines[1].strip()):
            lines[0] = title
            lines[1] = "=" * len(title)
            rst_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def setup(app):
    app.connect("builder-inited", run_apidoc)
